sudo: false
language: python
# Existing Python versions
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
install:
  - pip install pep8
  # latest version seems broken with Python 2.6, no version seem to work with 3.2
  - if ! python --version 2>&1 | grep -q -e 'Python 2.6' -e 'Python 3.2'; then pip install rstcheck; fi
  # pyflakes seems broken with 2.6, 3.2 and 3.3, and as of 7 jan 2019
  # with Python 3.8. Keep the testsuite working with with these
  # versions but there's no need to run pyflakes with all versions.
  - if ! python --version 2>&1 | grep -q -e 'Python 2.6' -e 'Python 3.[238]'; then pip install pyflakes; fi
script: cd t/ && verbose=t make all && ! git status --porcelain | grep -e '^??'
